# Generated by Django 5.0.6 on 2024-06-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_manufactured_at_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufactured_at",
        ),
    ]
