# Generated by Django 5.0.6 on 2024-07-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_product_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.IntegerField(default=0, verbose_name="Номер версии"),
                ),
                (
                    "name_version",
                    models.CharField(max_length=150, verbose_name="Название версии"),
                ),
                (
                    "indicates_version",
                    models.BooleanField(
                        default=True, verbose_name="Признак текущей версии"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["number_version", "name_version", "indicates_version"],
            },
        ),
    ]
