# Generated by Django 4.2 on 2024-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name", "product_category", "price"],
                "permissions": [
                    ("can_edit_product_description", "Can edit product description"),
                    ("can_edit_category", "Can edit category"),
                    ("can_edit_is_published", "Can edit is published"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Опубликован"
            ),
        ),
    ]
